version: "3.8"
services:
  db:
    image: postgres:12-alpine
    container_name: quickventory-go-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgsql-volume:/var/lib/postgresql/data:delegated
    networks:
      - quickventory

volumes:
  pgsql-volume:

networks:
  quickventory:
    driver: bridge
