
name: Release Image

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Build and push Docker image
        uses: pmorelli92/github-container-registry-build-push@2.0.0
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: backend
          docker-image-tag: ${{ steps.get_version.outputs.VERSION }}
